language: node_js
node_js: 8.9.4

matrix:
  include:
    - language: objective-c
      osx_image: xcode10.1
      xcode_sdk: iphonesimulator11.0

addons:
  artifacts: true

env:
  global:
  - NODE_VERSION=stable

install:
  - sudo launchctl limit maxfiles 2048 unlimited
  - sudo ulimit -n 10000
  - curl -o- https://raw.githubusercontent.com/creationix/nvm/v0.33.2/install.sh | bash
  - export NVM_DIR="$HOME/.nvm" && [ -s "$NVM_DIR/nvm.sh" ] && . "$NVM_DIR/nvm.sh"
  - nvm install $NODE_VERSION
  - nvm use $NODE_VERSION
  - cd ios/ && pod install && cd ..
  - brew install watchman
  - brew install yarn --without-node
  - brew tap wix/brew
  - brew install wix/brew/applesimutils
  - yarn global add react-native-cli
  - yarn global add detox-cli
  - yarn

script:
  - detox build --configuration ios.sim.release
  - detox clean-framework-cache && detox build-framework-cache
  - detox test --configuration ios.sim.release -l verbose --cleanup
