language: objective-c
osx_image: xcode9.4

env:
  global:
  - NODE_VERSION=stable
  - CODE_SIGNING_REQUIRED=NO

install:
  - sudo launchctl limit maxfiles 2048 unlimited
  - sudo ulimit -n 10000
  - curl -o- https://raw.githubusercontent.com/creationix/nvm/v0.33.2/install.sh | bash
  - export NVM_DIR="$HOME/.nvm" && [ -s "$NVM_DIR/nvm.sh" ] && . "$NVM_DIR/nvm.sh"
  - nvm install $NODE_VERSION
  - nvm use $NODE_VERSION
  - brew install watchman
  - brew install yarn --without-node
  - brew tap wix/brew
  - brew install wix/brew/applesimutils
  - yarn global add react-native-cli
  - yarn global add detox-cli
  - yarn
  - cd ios/ && pod install && cd ..
  - echo GOOGLE_API_KEY=$GOOGLE_API_KEY > .env

script:
  - detox build --configuration ios.sim.debug > /dev/null 2>&1
  - detox clean-framework-cache && detox build-framework-cache
  - react-native start &
  - detox test --configuration ios.sim.debug -l verbose --cleanup
